// AUTO-GENERATED by `webjs types`. Do not edit. Regenerated from app/ routes.
//
// Augments @webjsdev/core so the Route href union, navigate(), and per-route
// params are typed for this app. Regenerated per machine (gitignored, like
// Next's .next/types). Re-run `webjs types` after adding or removing a route.
import '@webjsdev/core';

declare module '@webjsdev/core' {
  interface WebjsRoutes {
    "/": true;
  }
  interface RouteParamMap {

  }
}
